[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_PUBLIC_RECIPIENT_ADDRESS = "0xbCcf6DA049fe3Ab996Abb6f960174E266a9835f3"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
